# conda environment file for the meddatathon project instructions:
# conda env create -f environment.yml


# To update the environment after modifying this file:
# conda env update -f environment.yml --prune

name: meddatathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - jupyterlab
  - pandas
  - scikit-learn
  - plotly
  - altair
  - numpy
  - pip:
    - --index-url https://test.pypi.org/simple/
    - --extra-index-url https://pypi.org/simple/
    - eda_simplifier #https://ubc-mds.github.io/DSCI_524_Group38_EDAsimplifier/
    - Missingness_Analyzer

